export default [
    'Yes',
    'No',
    'Of course',
    'Of course not',
    'Bad idea',
    'Good idea',
    'You are sure to have support',
    'You could find yourself unable to compromise',
    'Seek out more options',
    'Try something else',
    'Ask a friend',
    'Doubt it',
    'It will affect how others see you',
    "Don't wait",
    'Mishaps are highly probable',
    'Reprioritize what is important',
    'It would be inadvisable',
    'Setting priorities will be a necessary part of the process',
    'It would be better to focus on your work',
    "Don't bet on it",
    'Accept a change to your routine',
    'It will be a pleasure',
    'Finish something else first',
    'Let it go',
    "It is something you won't forget",
    'There is a small price to pay',
    "Follow someone else's lead",
    'It seem assured',
    'Trust your intuition',
    'You may have opposition',
    'Now you can',
    'It is worth the trouble',
    'Upgrade any way you can',
    'Startling events may occur as a result',
    'Only do it once',
    'Remain flexible',
    'Prepare for the unexpected',
    "You'll have to make it up as you go",
    'It will create a stir',
    'Better to wait',
    'Reconsider your approach',
    'You are too close to see',
    'It cannot fall',
    "You'll need to take the initiative",
    'Count to 10; ask again',
    "Don't be pressured into a acting too quickly",
    'Never',
    'Enjoy the experience',
    'Be patient',
    'Use your imagination',
    'Try a more unlikely solution',
    'Wait for a better offer',
    'Unquestionably',
    'Keep an open mind',
    'Wait',
    'There will be obstacles to overcome',
    'The outcome wil be positive',
    "Don't waste your time",
    'Be delightfully sure of it',
    'There is a substantial link to another situation',
    'Make a list of why not',
    "You will find out everything you'll need to know",
    'Maybe',
    'Deal with it later',
    'Laugh about it',
    'Leave behind old solutions',
    'No matter what',
    'Realize that too many choices is a s difficult as too few',
    'Adopt an adventurous attitude',
    'Provided you say "thank you"',
    'Speak up about it',
    'It is not significant',
    'Investigate and then enjoy it',
    'It is sure to make things interesting',
    'Do it early',
    'Follow the advice of experts',
    'Take more time to decide',
    "You'll need more information",
    'Be practical',
    'Watch and see what happens',
    'Assistance would make your progress a success',
    'It could be extraordinary',
    "You don't really care",
    'Avoid the first solution',
    "Don't be ridiculous",
    'Focus on your home life',
    "That's out of your control",
    'Remove your own obstacles',
    'Make a list of why',
    "It's good time to make plans",
    "Don't ignore the obvious",
    'It is significant',
    'Your actions will improve things',
    'There is no guarantee',
    'Definitely',
    "It'll cost you",
    'To ensure the best decision, be calm',
    'Trust your original thought',
    "Perhaps, when you're older",
    'Settle it soon'
]
